### ISSUE TITLE
Add support for custom headers in calls to Prometheus API

### ISSUE THREAD

**Issue by klagroix** [DevOps-Nirvana/Kubernetes-Volume-Autoscaler#13]
**Is your feature request related to a problem? Please describe.**

When using prometheus in [agentMode](https://github.com/prometheus-community/helm-charts/blob/cc2c507e4a4b625f561577bba13795b7f8bde40a/charts/kube-prometheus-stack/values.yaml#L2404-L2408), Volume Autoscaler will fail with the following error:

```
Prometheus query failed with code: error
Prometheus Error: unavailable with Prometheus Agent
```

When Mimir or Cortex is used as a prometheus datastore, it requires the `X-Scope-OrgID` header to be added to API requests.
References:
* https://grafana.com/docs/mimir/latest/operators-guide/secure/authentication-and-authorization/#grafana-mimir-authentication-and-authorization
* https://grafana.com/docs/mimir/latest/references/http-api/#authentication

Currently, Volume Autoscaler cannot be used to query Mimir running in multi-tenant mode.

**Describe the solution you'd like**

I'd like the option to provide the `X-Scope-OrgID` header. Ideally we could provide a map of any headers in the helm chart's `values.yaml` but any way to set `X-Scope-OrgID` would meet the current need.

**Describe alternatives you've considered**

The alternatives are to...
* Run prometheus in non-agent mode. This has it's own drawbacks
* Run mimir in single tenant mode. This isn't always possible
* Add some sort of translation layer/reverse proxy to inject the `X-Scope-OrgID` header

**Comment by AndrewFarley** [comment]
Thanks for this, this is a great feature request.  I will try to work on this over the weekend if I can

**Comment by AndrewFarley** [comment]
Implemented in https://github.com/DevOps-Nirvana/Kubernetes-Volume-Autoscaler/commit/200adbf59b46bc0efdeefebd77bee4d8f2b40cf2 will keep this open until I release the feature.

**Comment by klagroix** [comment]
That's wonderful. Thanks very much @AndrewFarley!
