### ISSUE TITLE
Customize Slack message

### ISSUE THREAD

**Issue by thof** [DevOps-Nirvana/Kubernetes-Volume-Autoscaler#15]
**Is your feature request related to a problem? Please describe.**
It'd be nice to be able to customize the message sent to Slack, as it currently lacks e.g. the K8s cluster name, so with multiple clusters having similar apps setup you don't know where the scale up event happened. Or at least for now optionally add the cluster name via values.yaml.

**Comment by AndrewFarley** [comment]
I've implemented this in https://github.com/DevOps-Nirvana/Kubernetes-Volume-Autoscaler/commit/e6170da0fa48522cb9e99ca9178b3b35c817db7a and hope to be releasing it shortly.  Will close this issue after I release it.

**Comment by AndrewFarley** [comment]
@thof This is now released in version [1.0.7](https://github.com/DevOps-Nirvana/Kubernetes-Volume-Autoscaler/releases/tag/1.0.7) please update your deployment and add your new slack message prefix/suffix.  I haven't yet added great documentation about this new feature to the README but I'll work on that shortly as well for you and the community as a whole.

Closing issue as resolved.  Please re-open or open an new one if there's any issues.
