### ISSUE TITLE
Trigger on inodes count

### ISSUE THREAD

**Issue by piec** [DevOps-Nirvana/Kubernetes-Volume-Autoscaler#18]
Hi,

Sometimes a volume is full because there is no free inode left, while the capacity usage is still low. This happens when you have lots of small files for example.
The feature request would be to add a new resize condition based on the inodes free/count ratio (based on `kubelet_volume_stats_inodes*` metrics for example)

Cheers,
Pierre

**Comment by AndrewFarley** [comment]
I've just implemented this, will test it shortly and then release it.

**Comment by AndrewFarley** [comment]
Released feature in [1.0.8](https://github.com/DevOps-Nirvana/Kubernetes-Volume-Autoscaler/releases/tag/1.0.8)

**Comment by piec** [comment]
Awesome :smiley:! I will also test it

**Comment by piec** [comment]
I tested it and it works for me :+1: , thanks

**Comment by AndrewFarley** [comment]
@piec Thanks for the awesome feature request!  I've never had to scale on tons of little files myself in recent history, but I've definitely had this problem in the past so it's good to be able to handle it for those rare use-cases and systems which needs lots of small files.  It was an easy add as well, so no worries!  Cheers!
